### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by nfiniteset** [ebdsa/candidates#2]
### Hosting
- [x] Host it
- [x] DNS stuff?

### Copy
- [x] Update all static copy
- [x] Do we have the latest candidates?
- [x] Candiate images

### Navigation
- [x] Add breadcrumbs
- [x] Responsive
- [x] Design polish

### Introduction
- [x] Get the data
- [x] Mark it up
- [x] Style it
- [x] Responsive
- [x] Design polish

### Position description
- [x] Get the data
- [x] Mark it up
- [x] Style it
- [x] Responsive
- [x] Design polish

### LC Candidate
- [x] Get the data
- [x] Mark it up
- [x] Style it
- [x] Responsive
- [x] Design polish
- [x] Get nomination data
- [x] Get images into data

### National Convention Intro
- [ ] Get the data
- [x] Mark it up
- [x] Style it
- [x] Responsive
- [x] Design polish

### National Convention Candidates
- [x] Get the data
- [x] Mark it up
- [x] Style it
- [x] Responsive
- [ ] Design polish
